global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker_healthcheck'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
